### ISSUE TITLE
Failed to install 'com-appliedrec-plugins-veridcredentials' from git path

### ISSUE THREAD

**Issue by sanitul** [AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin#19]
Hi @jakubdolejs,
we can not install Ver-ID-Credentials-Cordova-Plugin from git path. When we try to install the cordova plugin from git path using
`cordova plugin add https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git`

**we are getting the following error**

```
Installing "com-appliedrec-plugins-veridcredentials" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Installing "com-appliedrec-plugins-veridcredentials" for ios
Failed to install 'com-appliedrec-plugins-veridcredentials': undefined
CordovaError: Promise rejected with non-error: 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'
```
So we only have the plugin works, first cloning it and after the clone add it with a file path :( 

I would greatly appreciate it if you kindly give me some feedback on this
Thank you

**Comment by jakubdolejs** [comment]
Hi @sanitul, try to run `pod repo update` to update your pod spec repositories. Wait for it to finish and try again.

**Comment by haydursek** [comment]
We are still having issues with this. Please have a look at the error below upon initial install of the plugin.  This should install successfully upon initial install, which it currently does not.

`ionic cordova plugin add https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git --verbose                                                                                      01:11      11:49    04.12.19
  ionic:cli-utils:bootstrap local CLI 4.0.1 found at /Users/shahwaradmin/Documents/dev/js/meed-ionic/node_modules/ionic/package.json +0ms
  ionic:cli-utils Terminal info: { tty: true, ci: false } +0ms
  ionic:cli-utils CLI global options: { _: [ 'cordova', 'plugin', 'add', 'https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +702ms
  ionic:cli-utils:lib:environment Environment open. +0ms
  ionic:cli-utils:lib:project Project type from config: Ionic Angular 3 (ionic-angular) +0ms
  ionic:cli-utils Project name: undefined +40ms
  ionic:cli Context: { binPath: '/Users/shahwaradmin/Documents/dev/js/meed-ionic/node_modules/ionic/bin/ionic', libPath: '/Users/shahwaradmin/Documents/dev/js/meed-ionic/node_modules/ionic', execPath: '/Users/shahwaradmin/Documents/dev/js/meed-ionic', version: '4.0.1' } +0ms
  ionic:cli-utils:lib:integrations:cordova:config Using config.xml: /Users/shahwaradmin/Documents/dev/js/meed-ionic/config.xml +0ms
> cordova plugin add https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git --verbose --save
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git"
saving exact
Running command: npm install https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git --production --save-exact
Command finished with error code 0: npm install,https://github.com/AppliedRecognition/Ver-ID-Credentials-Cordova-Plugin.git,--production,--save-exact
Copying plugin "/Users/shahwaradmin/Documents/dev/js/meed-ionic/node_modules/Ver-ID-Credentials-Cordova-Plugin" => "/Users/shahwaradmin/Documents/dev/js/meed-ionic/plugins/com-appliedrec-plugins-veridcredentials"
Calling plugman.install on plugin "/Users/shahwaradmin/Documents/dev/js/meed-ionic/plugins/com-appliedrec-plugins-veridcredentials" for platform "android
Installing "com-appliedrec-plugins-veridcredentials" for android
Running command: /Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/android/cordova/version
Command finished with error code 0: /Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/android/cordova/version
Finding scripts for "before_plugin_install" hook from plugin com-appliedrec-plugins-veridcredentials on android platform only.
No scripts found for hook "before_plugin_install".
Install start for "com-appliedrec-plugins-veridcredentials" on android.
PlatformApi successfully found for platform android
Android Studio project detected
Beginning processing of action stack for android project...
Installing Android library: src/android/veridcredentials.gradle
Installing Android library: com.appliedrec:id-capture:5.0.4
Action stack processing complete.
Updating build files since android plugin contained <framework>
Subproject Path: CordovaLib
Subproject Path: app
Install complete for com-appliedrec-plugins-veridcredentials on android.
Finding scripts for "after_plugin_install" hook from plugin com-appliedrec-plugins-veridcredentials on android platform only.
No scripts found for hook "after_plugin_install".
Calling plugman.install on plugin "/Users/shahwaradmin/Documents/dev/js/meed-ionic/plugins/com-appliedrec-plugins-veridcredentials" for platform "ios
Installing "com-appliedrec-plugins-veridcredentials" for ios
Running command: /Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/ios/cordova/version
Command finished with error code 0: /Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/ios/cordova/version
Finding scripts for "before_plugin_install" hook from plugin com-appliedrec-plugins-veridcredentials on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "com-appliedrec-plugins-veridcredentials" on ios.
PlatformApi successfully found for platform ios
Beginning processing of action stack for ios project...
Action stack processing complete.
Adding pods since the plugin contained <framework>(s) with type="podspec"
pods.json found in platforms/ios
Podfile found in platforms/ios
Set pods.json for `Ver-ID-Credentials`
Added pod line for `Ver-ID-Credentials`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Running command: pod install --verbose
==== pod install start ====

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-meed`: (``)

Finding Podfile changes
  A Ver-ID-Credentials

Resolving dependencies of `Podfile`

[!] CocoaPods could not find compatible versions for pod "Ver-ID-Credentials":
  In Podfile:
    Ver-ID-Credentials (~> 2.1)

Specs satisfying the `Ver-ID-Credentials (~> 2.1)` dependency were found, but they required a higher minimum deployment target.

/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Command finished with error code 1: pod install,--verbose
Failed to install 'com-appliedrec-plugins-veridcredentials': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
pod: Command failed with exit code 1
Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/shahwaradmin/Documents/dev/js/meed-ionic/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.

        cordova plugin add https://github.com/AppliedRecognition/Ver-ID-Credentials-Cord... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 queued functions +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +1ms`

**Comment by jakubdolejs** [comment]
Hello @haydursek and @sanitul. Can you please verify that the minimum deployment target of your application is iOS 11 or newer?
